### ISSUE TITLE
Please check re-organisation of document

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfmp#12]
I suggest a re-organization of the Rmd files to better separate specifications of OM and MPs, to make the filenames more meaningful, and to accommodate other species.

I suggest that for each species, there are the following four files:
effort-shortraker.Rmd  (was effort.Rmd)
mp-specification-shortraker.Rmd (didn't have its own file)
om-specification-shortraker.Rmd (was description.Rmd)
runmse-shortraker.Rmd (was om.rmd)

They should probably all combine into one appendix per species (I haven't dealt with this)

I guess if we run each species sequentially, we won't need to rename all the objects to be unique to each species ...?

**Comment by robynforrest** [comment]
I have pushed these changes

**Comment by seananderson** [comment]
That sounds good. It needed a reorg like that. It’s a bit strange because the appendices contain full assessments that in themselves would contain appendices.

**Comment by robynforrest** [comment]
Right, I was thinking the same thing. We could treat the species as chapters, then they could have their own appendices

**Comment by robynforrest** [comment]
... but then we maybe run into the issue of object names having to be unique for each species ... we'll work it out.

**Comment by seananderson** [comment]
We’ll want unique object names anyways so that the automatic knitr chunk caching works.
