### ISSUE TITLE
DLMtool::runMSE error when parallel = TRUE

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfmp#13]
Failing here:

short_mse <- runMSE(OM = om, MPs = mp, parallel = TRUE)  

Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

Traceback:
26. | stop("numbers of columns of arguments do not match")
25. | rbind(deparse.level, ...)
24. | (function (..., deparse.level = 1)   .Internal(rbind(deparse.level, ...)))(obj1 = structure(list(A =   c(31113.1460075314, 4000.66770276056, 2125.26253993162, 15385.972729806,   597.170171466649, 853.744402566324, 14779.3656819004, 1772.48994198916,   7171.37359135851, ...
23. | do.call(rbind, templs)
22. | joinMSE(temp)
21. | runMSE(OM = om, MPs = mp, parallel = TRUE) at   <text>#4
-- | --

**Comment by seananderson** [comment]
Does it work with parallel = FALSE for you?

**Comment by robynforrest** [comment]
Yes it does

**Comment by seananderson** [comment]
So it's something with the parallel set up and the snowfall package. I know very little about parallel processing on Windows and all the parallel processing in R that I programmed myself has been with the foreach or future packages. @cgrandin probably knows more than is healthy about parallel processing and windows. Tom or Adrian may have encountered similar problems before.

**Comment by robynforrest** [comment]
OK, well I can proceed for now, if slowly, thanks for the suggestion! I'll touch base with Tom

**Comment by robynforrest** [comment]
According to our parallel guru, Windows doesn't support the parallel processing ...

**Comment by cgrandin** [comment]
My guess is that there's some system call happening, and Windows OS doesn't have the fork command which is required for that. I've run into this multiple times

**Comment by seananderson** [comment]
It does, just not necessarily in the same way as on Unix. I'm sure it's possible with snowFall and DLMtool since that's what they are using at UBC. There's a fairly long discussion here: https://cran.r-project.org/web/packages/future/vignettes/future-1-overview.html The future package is an amazingly slick way to work with parallel processing these days.

**Comment by robynforrest** [comment]
Here is Adrian's solution:
In parallel mode there are only a few sims running in each cluster - eg I have 10 cores & with 50 sims thats 5 simulations per core. The model stops if more than 5% of simulations fails to meet the specified depletion - in this case when only 1 simulation fails it is 20% of the simulations. 

Increasing the number of re-samples seems to fix the problem: MSE <- runMSE(OM, parallel=TRUE, ntrials=1000)
