### ISSUE TITLE
Slots we may choose to ignore

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#15]
I'm going to keep a list here of operating model slots that we could choose to not use or leave fixed at 0 for the purpose of simplifying the operating model descriptions for the review process. Feel free to add or modify. For the purposes of this "framework" document we could mention that these exist but are not being used.

### Period {#app:desc-stock-period}

*(Optional) Period for cyclical recruitment pattern in years. Uniform distribution lower and upper bounds. Non-negative real numbers*

### Amplitude {#app:desc-stock-amplitude}

*(Optional) Amplitude in deviation from long-term average recruitment during recruitment cycle (eg a range from 0 to 1 means recruitment decreases or increases by up to 100% each cycle). Uniform distribution lower and upper bounds. 0 < Amplitude < 1*

### AbsSelYears {#app:desc-fleet-absselyears}

*(Optional) Calendar years corresponding with SelYears (eg 1951, rather than 1), used for plotting only. Vector (of same length as SelYears). Positive real numbers*

### M2 {#app:desc-stock-m2}

*(Optional) Natural mortality rate at age. Vector of length maxage . Positive real number*

### Mexp {#app:desc-stock-mexp}

*Exponent of the Lorenzen function assuming an inverse relationship between M and weight. Uniform distribution lower and upper bounds. Real numbers <= 0.*

### Msd {#app:desc-stock-msd} (could choose to set to 0)

*Inter-annual variability in natural mortality rate expressed as a coefficient of variation. Uniform distribution lower and upper bounds. Non-negative real numbers*

### SelYears {#app:desc-fleet-selyears}

*(Optional) Years representing join-points (vertices) at which historical selectivity pattern changes. Vector. Positive real numbers*

### AbsSelYears {#app:desc-fleet-absselyears}

*(Optional) Calendar years corresponding with SelYears (eg 1951, rather than 1), used for plotting only. Vector (of same length as SelYears). Positive real numbers*

### L5Lower {#app:desc-fleet-l5lower}

*(Optional) Lower bound of L5 (use ChooseSelect function to set these). Vector. Non-negative real numbers*

### L5Upper {#app:desc-fleet-l5upper}

*(Optional) Upper bound of L5 (use ChooseSelect function to set these). Vector. Non-negative real numbers*

### LFSLower {#app:desc-fleet-lfslower}

*(Optional) Lower bound of LFS (use ChooseSelect function to set these). Vector. Non-negative real numbers*

### LFSUpper {#app:desc-fleet-lfsupper}

*(Optional) Upper bound of LFS (use ChooseSelect function to set these). Vector. Non-negative real numbers*

### VmaxLower {#app:desc-fleet-vmaxlower}

*(Optional) Lower bound of Vmaxlen (use ChooseSelect function to set these). Vector. Fraction*

### VmaxUpper {#app:desc-fleet-vmaxupper}

*(Optional) Upper bound of Vmaxlen (use ChooseSelect function to set these). Vector. Fraction*

### MPA {#app:desc-fleet-mpa}

*(Optional) Matrix specifying spatial closures for historical years.*

**Comment by seananderson** [comment]
Somewhere in the R package (in `inst/`) we will need to have a .csv file with alternate descriptions for the slots (for those lots that need alternate descriptions) and a column for including or not including them in the template. Alternatively, our template generating function could have an argument of slots to ignore. That may make it easier to choose to include one of these ignored slots for a given stock in the future.

**Comment by robynforrest** [comment]
I like the idea of a list of slots to ignore. I think many of the slots have been put there for bespoke purposes. If we list all of them with null or zero values, it will look as if these are all valid options, when some are simply irrelevant for a particular stock. Agree with keeping it simple and reporting on what we did rather than what we didn't do

**Comment by cgrandin** [comment]
I'm have been setting up the custom definition file and code today and am thinking that this file should be editable on a per-stock basis, so there has to be a mechanism to copy it from inst into a working folder when the package is installed

**Comment by cgrandin** [comment]
195bad1b8a126e185ec8bdc656a817a2d59859c8 to add custom descriptions

**Comment by seananderson** [comment]
There are a number of similar slots in the observation model that we could make some consistent decisions on to simplify things. For example, LenMbiascv, Mbiascv, Kbiascv, t0biascv, Linfbiascv, LFCbiascv, LFSbiascv, FMSYbiascv, FMSY_Mbiascv, BMSY_B0biascv, Irefbiascv, Brefbiascv, Crefbiascv, Dbiascv, hbiascv, Recbiascv.

The default for the `Precise_Unbiased` and `Imprecise_Unbiased` observation models is `c(0.05, 0.05)` for most of these and `c(0.1, 0.1)` for some.

Keep in mind that these are all for "persistent bias". I.e. for a given simulation draw the observation of a given parameter may be consistently high or consistently low but on average at the expectation.

I can't think of how we would justify most of these via data so I guess we just need to pick some moderate values and use those consistently barring some specific information for a given stock or consider setting many of these to 0 to effectively eliminate them and simplify the model.

Note that the defaults in many cases seem to be set up as a single value but I presume these get turned into a numeric vector of length 2.

```
> DLMtool::Precise_Unbiased
An object of class "Obs"
Slot "Name":
[1] "Precise-Unbiased"

Slot "Cobs":
[1] 0.1 0.2

Slot "Cbiascv":
[1] 0.05

Slot "CAA_nsamp":
[1] 150 300

Slot "CAA_ESS":
[1]  50 100

Slot "CAL_nsamp":
[1] 150 300

Slot "CAL_ESS":
[1]  50 100

Slot "Iobs":
[1] 0.10 0.25

Slot "Ibiascv":
[1] 0.1

Slot "Btobs":
[1] 0.05 0.20

Slot "Btbiascv":
[1] 0.333 3.000

Slot "beta":
[1] 0.666 1.500

Slot "LenMbiascv":
[1] 0.05

Slot "Mbiascv":
[1] 0.05

Slot "Kbiascv":
[1] 0.05

Slot "t0biascv":
[1] 0.05

Slot "Linfbiascv":
[1] 0.05

Slot "LFCbiascv":
[1] 0.05

Slot "LFSbiascv":
[1] 0.05

Slot "FMSYbiascv":
[1] 0.1

Slot "FMSY_Mbiascv":
[1] 0.25

Slot "BMSY_B0biascv":
[1] 0.1

Slot "Irefbiascv":
[1] 0.1

Slot "Brefbiascv":
[1] 0.1

Slot "Crefbiascv":
[1] 0.1

Slot "Dbiascv":
[1] 0.2

Slot "Dobs":
[1] 0.025 0.100

Slot "hbiascv":
[1] 0.1

Slot "Recbiascv":
[1] 0.05 0.10
```

```
> DLMtool::Imprecise_Unbiased
An object of class "Obs"
Slot "Name":
[1] "Imprecise-Unbiased"

Slot "Cobs":
[1] 0.2 0.6

Slot "Cbiascv":
[1] 0.05

Slot "CAA_nsamp":
[1]  50 100

Slot "CAA_ESS":
[1] 10 20

Slot "CAL_nsamp":
[1]  50 100

Slot "CAL_ESS":
[1] 10 20

Slot "Iobs":
[1] 0.2 0.6

Slot "Ibiascv":
[1] 0.1

Slot "Btobs":
[1] 0.2 0.5

Slot "Btbiascv":
[1] 0.333 3.000

Slot "beta":
[1] 0.666 1.500

Slot "LenMbiascv":
[1] 0.05

Slot "Mbiascv":
[1] 0.05

Slot "Kbiascv":
[1] 0.05

Slot "t0biascv":
[1] 0.05

Slot "Linfbiascv":
[1] 0.05

Slot "LFCbiascv":
[1] 0.05

Slot "LFSbiascv":
[1] 0.05

Slot "FMSYbiascv":
[1] 0.1

Slot "FMSY_Mbiascv":
[1] 0.25

Slot "BMSY_B0biascv":
[1] 0.1

Slot "Irefbiascv":
[1] 0.1

Slot "Brefbiascv":
[1] 0.1

Slot "Crefbiascv":
[1] 0.1

Slot "Dbiascv":
[1] 0.2

Slot "Dobs":
[1] 0.05 0.20

Slot "hbiascv":
[1] 0.1

Slot "Recbiascv":
[1] 0.1 0.3
```

**Comment by seananderson** [comment]
I turned off a number of slots by default here: https://github.com/pbs-assess/gfdlm/commit/8442e0cb4c564a8eb0c3982e1e6d2de86df2e1e2

I will make a section of the report describing what these are set to by default.

**Comment by robynforrest** [comment]
I am starting a section describing generic slots for the OM sub-components

**Comment by robynforrest** [comment]
Ksd, Linfsd and Msd need to be set to true. runMSE fails without them. My base pcod om (not the SRA version) was built after the om specification Rmd files were stripped and the MSE won't run with it.
