### ISSUE TITLE
Add suffix to chunk names in generated .rmd file

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/gfmp#18]
Add a suffix for a species to the chunk name, or possibly replace one which was previously added. See XXXX below

```r
<!-- autogen-begin -->
### Name {#app:desc-stock-name-XXXX}

*The name of the Stock object. Single value. Character string*
<!-- autogen-end -->
```

**Comment by cgrandin** [comment]
main code in c412518aa421a48e117269c322ee1012849818e7 but completed in f707287c086b3d25b209c50c3368e18ee9f88de5

```r
change_rmd_suffix("report/om-specification-shortraker.Rmd", "newsuffix")
```
to add or swap to the new suffix in all tags and code chunk names or

```r
change_rmd_suffix("report/om-specification-shortraker.Rmd")
```
to remove them all.

**Comment by seananderson** [comment]
Awesome. Thanks.
