### ISSUE TITLE
oldpar?

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfmp#19]
Very small issue. 

L172 of runmse-shortraker the object oldpar is created. It is then used in the next chunk.

This was commented out so the next chunk could not run. I am not sure what the par() function does but oldpar needs to be in both chunks or deleted from both chunks. oldpar is not used anywhere else.

```{r}
 #plot(short_mse)
 #**oldpar <- par()**
##DFO_hist(short_mse)
par(mfrow = c(1, 1))
DFO_plot(short_mse)
# DFO_plot2(short_mse)
```
```{r, fig.asp=1, warning=FALSE}
DFO_proj(short_mse)
#
...
#
**par(oldpar)**
```

**Comment by seananderson** [comment]
Yeah, don’t need it now. Can delete. The par settings are reset inside the DLMtool functions now (at least in the GitHub version).
