### ISSUE TITLE
Stan VB aging-error

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/gfmp#2]
I'm looking at the **aging error** Stan part from the Shortraker example and trying to see how this has been worked into *gfplot*. Bottom line is a can't figure out how to get the CV to be included. It seems like it has been implemented in the stan files for *gfplot* but not included in the R part of *gfplot*, is that right? 

I'm looking at **gfplot::fit_vb()** and the files **aging-error.stan**, and **vb_aging_error_gamma.stan**

**Comment by seananderson** [comment]
It's not integrated in gfplot. I might even strip out the basic Stan model from gfplot soon. I'd just use the values derived from the models already fit in pbs2dlm (or whatever that is called right now) and output in that DLMtool data object. That's from a TMB model. I wouldn't worry about the cpars part.
