### ISSUE TITLE
Check why Pcod VB growth pars are different in gfmp compared to Pcod assessment

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfmp#20]
Area of interest is "SYN HS", "SYN QCS".  I tried running the mcmc version of fit_vb in gfmp and it gives very similar results to the non-mcmc version in gfmp. Therefore we have differences in data, which shouldn't really happen as we only have a few years of ageing data ...

Could it be because we are filtering by survey in the assessment and by area in gfmp?

**Assessment:**
x <- filter(d$survey_samples,  is.element(survey_abbrev, c("SYN HS", "SYN QCS","SYN WCVI")))
surveys_list <- list(
  `SYN HS, SYN QCS, SYN WCVI` = c("SYN HS", "SYN QCS","SYN WCVI"),
  `SYN HS, SYN QCS` = c("SYN HS", "SYN QCS"),
  `SYN WCVI` = "SYN WCVI"
)

sexes <- c("all")
vb_fits <-
  map(surveys_list, function(.survey) {
    map(sexes, function(.sex) {
      .dat <- filter(x, is.element(survey_abbrev, .survey))
      **fit_vb(.dat, .sex, method = "mcmc", chains = 4L, iter = 2000L,
        uniform_priors = TRUE, seed = 1,
        cores = parallel::detectCores(),
        control = list(adapt_delta = 0.99, max_treedepth = 20L))**
    })
  })

**gfmp:**
pcod_areas <- c("05","06","07","08") #QCS and HS for comm samples, surv samples and catch
.dpc$survey_samples <- gfplot::get_survey_samples(species_name)
.dpc$survey_samples <- .dpc$survey_samples %>% 
  filter(major_stat_area_code %in% pcod_areas)
mvb <- gfplot::fit_vb(.dpc$survey_samples, sex = "all")

**Comment by seananderson** [comment]
Maybe. Can you compare the raw data going into the models?

**Comment by seananderson** [comment]
The Stan MCMC model hasn't changed at all, although note that the `uniform_priors` was used in the assessment and that it needed a ton of iterations with a high `adapt_delta` value to converge. The maximum likelihood model has changed. It used to find the maximum a posteriori probability (MAP) estimate via Stan. It now uses TMB. I realized there were problems for some stocks with the Stan MAP version and of the TMB one is more robust (although it too can be sensitive to starting values... these vB models can be nasty).

Other than that if there are any changes then it's almost certainly the data.

**Comment by robynforrest** [comment]
I'm pretty sure it must be the data. I'm too tired to check it right now ... I opened the issue to remind myself to go back to it ...

**Comment by robynforrest** [comment]
I ran both the "old" MCMC and the "new" ML model with the gfmp dataset and got similar results so it's the data for sure
