### ISSUE TITLE
Add mechanism to include or exclude and order slots

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#21]
Could be a bit trickier. 

At the same time, might be worth adding an order column to the csv so we can choose to group the slot descriptions differently. 

Doesn’t necessarily have to be able to reorder existing .rmd files.

**Comment by cgrandin** [comment]
I didn't do any re-ordering of the shortraker or pcod files, just wrote the function to do so. The steps are:
- modify the two csv files in pbs2dlm/inst
- reinstall the package and then:
```r
create_rmd("report/om-specification-pcod.Rmd")
```
