### ISSUE TITLE
P cod sample data seems incomplete before 1996

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfmp#22]
d_pc$commercial_samples <- gfdata::get_commercial_samples(species_name)
pcod_areas <- c("05","06","07","08") #QCS and HS for comm samples, surv samples and catch
d_pc$commercial_samples <- d_pc$commercial_samples %>% 
  filter(major_stat_area_code %in% pcod_areas)

For 5ABCD P cod there are only length samples for some years prior to 1996 (e.g., 1992-1995 missing). Only 37 years with samples between 1956 and 2018. Looking at the P cod res doc there should be much more data than that. Are we getting all the data from the older databases?

The code for calculating annual mean weights isn't in the P cod res doc files, as we didn't actually report the results.

**Comment by robynforrest** [comment]
Or is it something to do with the filtering? I don't know the numbered area codes or if they were different in older databases

**Comment by seananderson** [comment]
Is it a sorted / unsorted thing? Default is unsorted only. The tidying functions are then removing anything that isn’t sexed currently. The only other option would be that Elise recently noticed that best_length includes multiple types of measurements and the function now just takes the most common.

**Comment by robynforrest** [comment]
I tried this but still get unsorted only
  d_pc$survey_samples <- gfdata::get_survey_samples(species_name,unsorted_only = FALSE)

**Comment by seananderson** [comment]
There may not be any sorted survey sample data for p cod. I would expect there to be a difference for the commercial samples though. It could come down to the new filtering on types of measurements. @elisekeppel could you look into this?

**Comment by robynforrest** [comment]
OK thanks - yes I was trying to do two things at once yesterday. 
d_pc$commercial_samples <- gfdata::get_commercial_samples(species_name,unsorted_only = FALSE)
> unique(d_pc$commercial_samples$sampling_desc)
[1] "DISCARDS" "KEEPERS"  "TBD"      "UNSORTED"

**Comment by seananderson** [comment]
Discards, keepers, and TBD are your "sorted" samples.

**Comment by seananderson** [comment]
Are you still missing samples before 1996?

**Comment by seananderson** [comment]
@elisekeppel Is looking into how many specimens are lost by the use of a single length type for p cod. With a conversion ratio we could use all of them.

**Comment by elisekeppel** [comment]
Most of the length measurements are fork length - we only lose some lengths in 2010 and a few in 2017 from selecting only fork lengths. The pre-1996 data are the same. 

I'll check into the filtering, particularly the sorted/unsorted stuff.

**Comment by robynforrest** [comment]
I was just re-organizing files, now back to this. I will explore more too

**Comment by robynforrest** [comment]
Still something strange going on. tidy_cal gives different years with data compared to tidy_mean_length even though both using the same data ... I think.

See Lines 55 onwards of sra/build-data-objects.Rmd.

Have to go but back later tonight

**Comment by seananderson** [comment]
tidy_cal is set up to always only use the unsorted samples right now; you could change it

**Comment by robynforrest** [comment]
Where is tidy_cal?

**Comment by seananderson** [comment]
Here:
https://github.com/pbs-assess/gfmp/blob/master/pbs2dlm/R/convert.R#L183-L242

These are still half-baked.

**Comment by robynforrest** [comment]
Thanks - the one file in that folder I didn't look at

**Comment by seananderson** [comment]
It looks like the length one was set up to use unsorted only but the age one was set up to use all samples.

**Comment by robynforrest** [comment]
Oh so it already has an unsorted_only argument so I can just change it in the function call?

**Comment by seananderson** [comment]
Yep, it looks like it. Although I guess it would make sense if the defaults were the same for the two functions.

**Comment by robynforrest** [comment]
Yes, unsorted is probably the best default ... leave it up to the user to opt to use potentially biased sorted data

**Comment by robynforrest** [comment]
I removed the female only filter in tidy_mean_length in convert.R. I was losing several years of recent data for p cod. Maybe this should be an optional argument?

**Comment by seananderson** [comment]
Yes, feel free to remove it. We can do our our own filtering before. There may be an argument for keeping the sorted argument, but we probably don't need anything else.
