### ISSUE TITLE
Performance metrics

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfmp#27]
Here are the current performance metrics from Sean's documentation:
1. PNOF: Probability of not overfishing P(F < FFMSY) (years 1–50)
2. P100: Probability SB > SBMSY (years 1–50)
3. P40: Probability SB > 0.4 SBMSY (years 1–50)
4. LTY: Probability yield > 0.5 MSY (years 41–50)
5. AAVY: Probability AAVY (average annual variability in yield) > 0.2

I think AAVY should be Probability AAVY (average annual variability in yield) < 0.2 so that it represents "desirable" performance.

Also think we need some short-term versions of LTY and AAV. From experience, these are important for stakeholders to see. i.e.,  what do their short-term losses look like for long-term gain? Suggest Years 5-20 or 5-25 as a first cut

**Comment by seananderson** [comment]
AAVY is actually < 0.2 right now. Sorry, that was a typo in that write up. 

Agreed that some short-term performance metrics would be good. It would be nice not to have too many performance metrics for the sake of plotting although we can always choose to just show a selected set of performance metrics in things like radar plots, especially if short-term and long-term gains/losses don't tell different stories.

**Comment by robynforrest** [comment]
Yes perhaps show the short term LTY and AAV metrics with the long term biomass metrics. I think that is what we did in the mseR paper. I think it is a legitimate question for industry to ask what they are "paying" in terms of benefiting fishers 1-2 generations away. Anyway, I think they will have a say in it. We just need to defend our initial choices.

**Comment by robynforrest** [comment]
Hmm. Looks like my radar plots used long-term average catch.
 But I did present both short and long term yield-based metrics in other plots and tables. I only showed long-term biomass metrics.
