### ISSUE TITLE
Add sections on C-68 to doc

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfmp#28]
A challenge/opportunity with Bill C-68 is demonstrating we are meeting requirements, particularly Section 6.1(1), which this report directly addresses.  
6.1 (1) In the management of fisheries, the Minister shall implement measures to maintain prescribed major fish stocks at or above the level necessary to promote the sustainability of the stock, taking into account the biology of the fish and the environmental conditions affecting the stock.

Add section in intro on how this work addresses C-68 for data-limited speces
Add section in conclusions reiterating how results specifically address C-68 requirements

**Comment by seananderson** [comment]
We discussed adding paragraph or small section in intro. Adding meatier section after description of the approach steps. Reiterate as it comes up in discussion. Likely call it ‘amended fisheries act’ with reference to the bill or something that will make more sense in the long term than Bill C68.

**Comment by robynforrest** [comment]
Suggested wording from Rob on how to refer to Bill C-68 provisions:
“amended Fish Stocks provisions in the Fisheries Act that resulted from the passage of Bill C-68”  ?

If Bill C-68 has passed, it is just the “Fish Stocks provisions of the Fisheries Act” (then you cite the Fisheries Act).

**Comment by robynforrest** [comment]
New text added to new introduction in introduction_new.Rmd
