### ISSUE TITLE
Develop rex sole OM

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#33]
Pick a stock unit. Look at value of information (aging).

**Comment by robynforrest** [comment]
Rex isn't listed in the IFMP table. I have emailed Rob Tadey to get more info on management areas

**Comment by robynforrest** [comment]
One spanner in the works is that there is no TAC at all for Rex. I think at some point we need to think about species not currently under quota, and this one has relatively large catches considering it is not under quota so I think it is worth doing. Looks like WCVI has the largest survey catch and commercial CPUE so I suggest we either do WCVI or CW
