### ISSUE TITLE
Adapt the current outline into the working paper .Rmd files

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#41]

**Comment by robynforrest** [comment]
I can do this over the next day or so

**Comment by robynforrest** [comment]
Working on this today

**Comment by robynforrest** [comment]
Made a start on this in introduction_new.Rmd. Edited/rewrote/re-organised all the existing text in the introduction and have added new headings from the current outline. Will continue to work on it this week. Currently the Rmd file builds as a standalone html file just for easy editing.

**Comment by robynforrest** [comment]
Do we need to add a Methods section? Somewhere to give an overview of DLMtool and how it works as well as how we will be evaluating the MPs

OR

Do we want to integrate it into the section "How the proposed approach adopts these best practices", like they did in the DLMtool paper?

AND/OR maybe we rename the section to "Methods: How the proposed approach adopts these best practices"

It seems strange to have a Res Doc without a Methods section

**Comment by seananderson** [comment]
Yes, I think that is our methods. Presumably the main text will introduce the DLMtool package at the appropriate location at a high level and there is a planned appendix to get into more details.

We could even just name it methods with the content structured in the format of how the proposed approach adopts the listed best practices.

**Comment by robynforrest** [comment]
Yes I think that's a good idea. We can follow the same approach in the DLMtool paper. Maybe even reproduce their Figure 1.  I am re-reading the Punt paper then will start writing. I agree let's stick with the Punt steps. We can add the Landmark Step 1 (define decision context) as Punt doesn't have that one. 
![image](https://user-images.githubusercontent.com/2694518/60301121-691dbc80-98e5-11e9-95e5-d039b521c1c8.png)
