### ISSUE TITLE
Adapt the shortraker case study to be for a single stock unit

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#42]
Defining a stock unit as one of the synoptic trawl survey domains.

**Comment by seananderson** [comment]
WCHG would be the most "data rich" in terms of survey observations and length samples. WCVI would be next although they are only caught in the survey in the deepest waters. HS would be near impossible to do on its own based on anything to do with the survey. QCS might be possible but there's only an average of 7/238 positive sets. The fisheries aren't catching them in HS at all either.

**Comment by robynforrest** [comment]
Hmm, it's managed as a CW stock. I guess the OM could be based on all surveys but maybe for the MP we could get agreement on the "best" or most representative survey of biomass and use that? Perhaps we need a process for doing that. Of course people are going to look at the one which goes up the most (if both are going up and both in the same direction), but maybe there is an "objective" method to pick the most representative survey?

**Comment by seananderson** [comment]
Lowest survey CV, highest relative biomass densities, high commercial catches, ...
