### ISSUE TITLE
Decide on a catch reconstruction (shortraker) and finish the write up

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#43]
Could go with the modelled version I was working on. Could also look at the algorithms that Rowan has used.

If going with the machine learning version I was working with before, then need to think more about the lognormal bias correction.

For this stock (shortraker), the catch time series might be a useful dimension to look at as part of a robustness set.

An alternative to anything fancy is to just include some different scenarios (e.g. divide catch between 1990 and 1995 by 1, 2, or 3).

**Comment by robynforrest** [comment]
I think go with the modelled version ... bonus is you can publish it, and keep developing it as needed if you receive feedback. And yes, it would seem the catch construction is a major axis of uncertainty for this stock so could replace the problematic period with a simple approach. If Rowan's algorithm returns something similar to yours, I don't see a lot of value in duplicating it.

**Comment by seananderson** [comment]
@elisekeppel , can you try Rowan's algorithm for shortraker for comparison?
