### ISSUE TITLE
Move our growing body of functions into a package (with a good name)

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#44]
I had started pbs2dlm but I think the data conversion function is just one part of this family of functions. Most of it is going to be plotting functions with a few custom performance metrics and some helpers for manipulating the output. Plus some helpers for getting our data into the correct format.

If we had a good name then we could make a separate repository or name the one in this repository something better.

- gfdlm
- gfdlmtool
- gfdlmtools
- pbsdlm

Presumably most of the functions we are working on are usable beyond groundfish, but it's also our collection of functions that, at least for now, we plan to use with groundfish.

**Comment by robynforrest** [comment]
I like pbsdlm. I think it tells users where it came from and it doesn't restrict the functions to gf necessarily. Also explicitly speaks to the dlm application

**Comment by cgrandin** [comment]
I made gfdlm before your comment Robyn. Is that ok? seems to fit with our gf* naming convention of late
