### ISSUE TITLE
Wrap up exploration of DLMtool::DD_ and look at DD MP in MSEtool

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfmp#48]

**Comment by robynforrest** [comment]
Figure out why myDLDD isn't working as an MP

**Comment by seananderson** [comment]
I can't run the whole script because `sra/pcod_no_comps_om_Mbias.rds` isn't committed/pushed to the repository, but when I substitute:

```r
ompc@nsim <- 20L
# setup()
pcod_mse <- DLMtool::runMSE(OM = ompc, MPs = "myDLDD", ntrials = 1000, PPD = TRUE, parallel=FALSE)
```

On line 225 to 227 of `DD_investigation.Rmd` it seems to run for me.

**Comment by robynforrest** [comment]
OK I will try again. rds files are on the gitignore list so I will send the om via slack

**Comment by robynforrest** [comment]
Just updated DLMtool. I get "Error: All MPs failed." using all three OMs (the two SRA OMs and the basic OM). Not a priority for now.
