### ISSUE TITLE
Fix Fox model equation

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#56]
n = 1 is a special case:

https://github.com/tcarruth/MSEtool/blob/e3c012781f880bff9ce0116741d8aceef67ee13b/inst/include/SP.hpp#L46-L47
https://github.com/tcarruth/MSEtool/blob/e3c012781f880bff9ce0116741d8aceef67ee13b/inst/include/ns/ns_SP.hpp#L16-L17

**Comment by quang-huynh** [comment]
This commit should have the proper Fox model equations https://github.com/tcarruth/MSEtool/commit/38e6efe50d740cfcc22d4a9576952acf7c75cf81

**Comment by seananderson** [comment]
Awesome. Thanks. That was fast.
