### ISSUE TITLE
Write simple how-to vignette(s)

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfmp#57]
It would be very useful to have a few little vignettes for our use with instructions on things like:
How to modify an MP
How to find and view key parameters or model variables to enable plotting ... like where is cpars??? ;-)
How to populate an OM rmd file using the tool
How to find and view specific DLMtool/MSEtool functions and code
How to find vignettes ... e.g., I just found this in Quang's Fox vignette browseVignettes("MSEtool")
Work flow from OM to SRA to MSE
...
Maybe we can go through these things when we meet early Feb and I can write up the steps

**Comment by seananderson** [comment]
Yes. And for some of that, the user guide:
https://dlmtool.github.io/DLMtool/userguide/introduction.html
