### ISSUE TITLE
Recommend how species would be selected for the framework and "graduate" out

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#60]
> There was also a recommendation to discuss and document process of how species would be selected for data-limited assessment via the MP Framework and how a species could be moved out of the Framework to have more data-rich, conventional assessments. While the availability of quality age-composition data would be the first consideration, this will likely need to be done on a stock-by-stock basis, and in consultation with science, managers, stakeholders, and other interested parties.

**Comment by robynforrest** [comment]
Add to VOI section of discussion
