### ISSUE TITLE
Add discussion of expected products

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#62]
> The authors agreed to improve documentation of what the products of the MP Framework are and how they can be used.

- research documents for 1 or small groups of related stocks
- likely science responses to update MP advice between OM reassessments
- science response could foreseeably include multiple stocks

**Comment by robynforrest** [comment]
This is not a topic for a res doc

**Comment by robynforrest** [comment]
Definitely discuss on meeting agenda
