### ISSUE TITLE
Add discussion of how multiple OMs will be considered in management recommendations

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#63]
> There was a recommendation to include discussion in the working paper of how alternative OMs would be treated in the management recommendations, for example, how would a decision proceed if an MP performs well (has acceptable trade-offs) under the reference set of OMs but performs poorly under the robustness OMs. Similarly, does performance under a worst-case OM scenario determine whether an MP is included as a management option? This would require some consideration of whether decision-making is risk-averse or risk-neutral and will require input from managers, stakeholders, and other interested parties.

Points to consider:
- minimax option (as current example uses)
- average performance?
- distinction between robustness and reference set
- what to do if an MP "fails" a robustness check

**Comment by robynforrest** [comment]
Bottom of Methods Step 6

**Comment by robynforrest** [comment]
I wrote a chunk on this under Step 6 in 03-Framework. Not sure if it is overstepping the role of science to say more. Rademeyer et al say that the ultimate MP needs to be robust to the robustness scenarios. I have cited that so maybe we can leave it there.
