### ISSUE TITLE
Add discussion of plan to check projections against OM

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#64]
> There was discussion and agreement from the authors to include a section of recommendations for the implementation stage of the Framework, once an MP has been selected. The authors agreed that it will be important to monitor and compare OM projection results with future observations (e.g., survey indices) and determine when an OM re-evaluation should be triggered. For example when observed indices fall outside the projected index beyond some agreed threshold. Tools for doing this are already available in the software. This is also important because recommending triggers for re-assessment is a CSAS requirement of most stock assessments and is included in the Terms of Reference for the Inside Yelloweye Rockfish Rebuilding Plan, which is the first application of the MP Framework, due for CSAS review immediately after the MP Framework CSAS review.

Consider Tom/Adrian's paper.

**Comment by robynforrest** [comment]
Pretty much done. Waiting for sablefish info
