### ISSUE TITLE
Add episodic recruitment robustness scenario in shortraker case study

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#66]
Or, if not doing this, make sure to mention it as an example robustness scenario for rockfish species

**Comment by robynforrest** [comment]
This would be a good idea for YE

**Comment by quang-huynh** [comment]
@robynforrest I agree.

@seananderson I've tried sampling rec devs using a t-distribution in log space but I don't think I can get an analytical solution for the bias correction to transform to normal space. Would sampling from two lognormal distributions, e.g. sigma = 0.4 mostly but occasionally sample from sigma = 1, be a suitable alternative to the wide tail distribution?

**Comment by seananderson** [comment]
@quang-huynh, hmm, good point. At very small degrees of freedom the t-distribution doesn't even have an expected mean. At moderate to large degrees of freedoms the bias correction would approach the normal. I assume this has been worked on somewhere.

Yes, a mixture of 2 normals would be fine, and is usually easier to explain anyways. (The t can be represented as a mixture of normals https://www.johndcook.com/t_normal_mixture.pdf)

Might need a more extreme 2nd distribution than 0.4 and 1 though. E.g. see the latest Bocaccio assessment:

Log space:
![image](https://user-images.githubusercontent.com/19349/73780015-87cd1700-4742-11ea-9119-d6741f4753f8.png)

Natural space:
![image](https://user-images.githubusercontent.com/19349/73780035-93204280-4742-11ea-91a5-63dbe1c93690.png)

**Comment by robynforrest** [comment]
@cgrandin Was this ever dealt with for Hake? I remember it coming up at a scientific review meeting a few years ago

**Comment by robynforrest** [comment]
Might be worth looking at what sigma would be needed to reproduce Boccaccio? I think that's the most extreme case we have seen (I could be wrong)

**Comment by seananderson** [comment]
You have to give it a timeframe and probability to determine what secondary distribution sigma would be expected to give you that deviation. We probably don't want to go quite as extreme as Bocaccio, but maybe something where within the projection period we will usually see at least 1 or 2 deviations ~twice as extreme as the usual extremes from the first distribution.

**Comment by quang-huynh** [comment]
Sampling from a larger sigmaR doesn't necessarily give you a large cohort, but you could re-sample until you get 1-2 deviates with Z-score > 2.5 per MGT (as an example).

**Comment by seananderson** [comment]
If we selectively resample I think that would mess up the bias correction. We’d end up having to do some empirical bias correction (which would also work with the t). I would set it up so that on a pretty regular basis we get at least 1 major recruitment event in the projection. Sometimes we won’t, but that’s OK. We could discuss the finer points next week.
