### ISSUE TITLE
Document co-caught species in the species background section

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#73]
> There was a suggestion to document co-caught species in the species background section, which may be helpful if it is necessary to borrow life-history and fishery information (e.g., parameters from a similar species caught at similar depth, or information about ration of retained:released fish).

**Comment by elisekeppel** [comment]
New Function in gfdata to explore co-caught species: get_cocaught_species()

**Comment by seananderson** [comment]
We're also wondering about it quantitatively. I.e., how much are they caught with these species now and how much of these species used to be reported? We're trying to figure out ballpark how much they might have been discarded in the past.
