### ISSUE TITLE
Standardize terminology for spider/radar/kite plots

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#74]
Radar? :(

Our package is ggspider

**Comment by robynforrest** [comment]
Punt 2015 calls them Kite plots.
https://doi.org/10.1093/icesjms/fsv193

They are called Radar or Spider in a few R package plots. I am happy to defect from Team Radar, I would favour Kite so we are following Punt's recommendation (and so we don't trigger anyone's arachnophobia)

**Comment by seananderson** [comment]
https://en.wikipedia.org/wiki/Radar_chart
First reference:
Mayr, Georg von (1877), Die Gesetzmäßigkeit im Gesellschaftsleben (in German), Munich: Oldenbourg, p.78. Linien-Diagramme im Kreise: Line charts in circles.

On Google trends, spider and radar are about equally popular; kite barely makes it on the chart and is left off:
![image](https://user-images.githubusercontent.com/19349/73780799-ff4f7600-4743-11ea-8131-0b60981e00ef.png)

A lot of the radar references on google are because it's what Excel calls them. I may consider that a downside to "radar". ;)

Fascinating discussion here:
https://www.data-to-viz.com/caveat/spider.html

I do wonder if a parallel coordinate plot (basically just switching from polar to cartesian coordinates) or some sort of lollipop plot with multiple coloured lines would be a good alternative.

![image](https://user-images.githubusercontent.com/19349/73781217-b77d1e80-4744-11ea-824b-3b402caf0ad2.png)

![image](https://user-images.githubusercontent.com/19349/73781249-c237b380-4744-11ea-9337-2197fe159cc8.png)

![image](https://user-images.githubusercontent.com/19349/73781263-c794fe00-4744-11ea-9695-72ab210140e4.png)

We could present a provisional options and see what sticks/works for people over time.

I think we negate some of the spider/radar negatives by not shading in the polygon and by not generally having dramatically different values along the spokes since they are already satisficed.

**Comment by seananderson** [comment]
Throwing something else out there:

If we are going to attend to compress across the reference set in some places, dot and line plots could work. Something like this:

![image](https://user-images.githubusercontent.com/19349/73781995-1abb8080-4746-11ea-9a8d-fe8e01d3939a.png)

where the x axis represents different performance metrics and different colored dots and lines represent the different MPs. This would allow us to show the variability across MPs as well as the average. I might connect the the dots to make a hybrid parallel coordinate plot.

Or go the full multi panel route with MPs on the x axis:

![image](https://user-images.githubusercontent.com/19349/73782091-4b031f00-4746-11ea-863c-6f4e6c56a9a6.png)

**Comment by robynforrest** [comment]
I find the dot and bar charts (your last comment) hard to interpret in terms of easily seeing trade-offs. I quite like the bar plots ... maybe try those and the radars. Well if Kite doesn't register then I am back in team Radar! (if they'll have me back after my disloyalty)

**Comment by seananderson** [comment]
Parallel coordinate option:
![image](https://user-images.githubusercontent.com/19349/73786967-265f7500-474f-11ea-8a1b-9675e6c69da5.png)

Could even put a vertical line delineating the conservation and catch performance metrics.

One advantage (/disadvantage) to this type of plot is it is easier to zoom in on the relevant axis range to actually distinguish differences. Also a disadvantage because it can make it easy to focus on trivial differences. To be fair, 0 is a pretty extreme lower expectation of these performance metrics and probably doesn't need to be shown. It would need to be shown with a bar or lollipop plot though.

**Comment by seananderson** [comment]
Reminds me of the Walkers from the Clone Wars if you put them on their side :)

![image](https://user-images.githubusercontent.com/19349/73787269-c9b08a00-474f-11ea-927f-e5f6d57dde55.png)

**Comment by seananderson** [comment]
Playing with lollipop plots:

<img width="400" src="https://user-images.githubusercontent.com/19349/73787567-6d9a3580-4750-11ea-8280-12097ea3a941.png">

**Comment by robynforrest** [comment]
I like the lollipops. You could describe the parallel coordinates plot as a stretched out radar plot. Advantage is it allows you to see the spread (I assume among reps). Disadvantage is it's more work to read than the radar plot. Good candidate for "user study" focus group.

**Comment by robynforrest** [comment]
![image](https://user-images.githubusercontent.com/2694518/73788315-9ec73580-4751-11ea-893e-2d192d2a8ffe.png)

**Comment by seananderson** [comment]
Apparently those user studies have already been done and the radar plots are terrible at rapid and accurate comprehension (although appealing visually at first). I guess humans don't think well in polar coordinates.

The parallel coordinates version is a bit more accessible without the range line segments and a bit more accessible again without the dots.

I like to call this one "spiders on a wall"

![image](https://user-images.githubusercontent.com/19349/73788434-e0f07700-4751-11ea-8a05-b2b17a4c9c64.png)

**Comment by seananderson** [comment]
Better again without the unnecessary jittering if just lines:

![image](https://user-images.githubusercontent.com/19349/73788836-99b6b600-4752-11ea-947d-d4627497a6b8.png)

**Comment by robynforrest** [comment]
Really? I like the spiders on the wall (... but not the name! Yhey remind me of really big Australian spiders). I guess if we orient people towards the way to interpret them (further to the right is better). Definitely we should do some kind of survey in a room with people. 

Punt 2015 (Fig 4) also recommends pairwise scatter plots to show two-way trade-offs (average biomass v average catch; P(1 + biomass > x tonnes);  % Years with catch vs P(catch > x tonnes).

Pairwise plots allow you to see the shape of the trade-off surface

**Comment by seananderson** [comment]
Ribbon version for showing the average and range at once. (actually the range excluding the highest and lowest right now — e.g., figure skating judging)

I do find this less chaotic than the dodged dot and line version.

![image](https://user-images.githubusercontent.com/19349/73789310-6163a780-4753-11ea-98e4-fb2a80890af1.png)

Agreed that pairwise are nice for seeing trade-offs. If we limit the comparisons then it's doable.

**Comment by robynforrest** [comment]
That one is good. Could you put horizontal dotted lines at 50% and 95%? And maybe also at the threshold we defined for AAVC? If I am an industry person looking at that, I am going to look at the STC and LTC first then read back to the conservation metrics that are satisficed. If they are all satisficed wrt conservation metrics then I am just looking at STC and LTC (and maybe asking about what is driving the AAVC number)

**Comment by seananderson** [comment]
Or cobwebs hanging from a ceiling:

![image](https://user-images.githubusercontent.com/19349/73791265-d4bae880-4756-11ea-9b90-afff62677249.png)

OK, I'll show myself out...

AAVY threshold would likely be baked into the metric. I.e., instead of the default Pr(AAVY > 0.2), 0.2 would be specific to the stock.

**Comment by seananderson** [comment]
I assume this is the major comparison for our current performance metrics. Could instead do things like average catch, average biomass...

![image](https://user-images.githubusercontent.com/19349/73794930-4ba7af80-475e-11ea-9ac5-e26067619e68.png)

![image](https://user-images.githubusercontent.com/19349/73794970-5c582580-475e-11ea-94bb-1eceaa08cd99.png)

**Comment by robynforrest** [comment]
Lucky I don't personally suffer from arachnophobia ... in fact I think spiders are fascinating ... just not those huge Australian ones with loooong legs!

**Comment by robynforrest** [comment]
I like those trade-off plots

**Comment by robynforrest** [comment]
Prefer them without the error bars so you can see the shape

**Comment by seananderson** [comment]
Death-to-radar-plot links and papers for future reference:
https://www.data-to-viz.com/caveat/spider.html
https://towardsdatascience.com/ghosts-on-the-radar-why-radar-charts-are-easily-misread-dba00fc399ef
https://blog.scottlogic.com/2011/09/23/a-critique-of-radar-charts.html
http://www.cs.middlebury.edu/~candrews/showcase/infovis_techniques_s16/radar_chart/
https://link.springer.com/article/10.1007/s11205-012-0028-6

Actual user studies:
https://ieeexplore.ieee.org/document/5613430
https://ieeexplore.ieee.org/abstract/document/7192648

**Comment by robynforrest** [comment]
Some compelling arguments there, especially about the ordering and polygon area. Possibly less of a concern for satisficed MPs as we might expect them all to be behaving more similarly. I like the lollipops and the trade-off scatter plots without the error bars. And I do think we could still show the radars until the clients settle on the one(s) that have the most meaning to them. I think the various walker/spider on a wall/cobwebs hanging from the ceiling plots will suffer from similar problems to the radar plots.

**Comment by seananderson** [comment]
"Radar" has won and been replaced throughout, although these may be relegated to an alternative or dropped entirely eventually.

Current choice attached.

![g2](https://user-images.githubusercontent.com/19349/74495095-b4dca080-4e8b-11ea-97be-060169d5486f.png)
