### ISSUE TITLE
Choose catch vs. yield

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#75]
> Standardize terminology for catch vs yield. Arguments were made in favour of both. Catch is a more accessible term. yield is consistent with terminology such as MSY, *F*~MSY~ and *B*~MSY~.

**Comment by robynforrest** [comment]
I don't know if we need to *fully* standardize these. Punt 2015 uses Catch in his performance statistics https://doi.org/10.1093/icesjms/fsv193  I would tend to prefer catch. But I think it is okay for it to be inconsistent with MSY, FMSY and BMSY ... these are long-term equilibrium concepts anyway and our stakeholders seem mostly comfortable with the different terminology.   So my vote is catch everywhere except MSY, BMSY, FMSY.

**Comment by seananderson** [comment]
Here's one possibility:

```
PM <- c("LT LRP", "LT USR", "ST Catch", "LT Catch", "AAV Catch", "FMSY")
```

I'm pretty happy with that other than perhaps "AAV Catch". 

or keep the very convenient "Y":

```
PM <- c("LT LRP", "LT USR", "STY", "LTY", "AAVY", "FMSY")
```

or

```
PM <- c("LT LRP", "LT USR", "STC", "LTC", "AAVC", "FMSY")
```

**Comment by robynforrest** [comment]
My vote
PM <- c("LT LRP", "LT USR", "STC", "LTC", "AAVC", "FMSY")

**Comment by seananderson** [comment]
Catch has won except in the case of MSY.
