### ISSUE TITLE
Declare spawning stock biomass as B and use B (not SSB) throughout

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#80]
- Just for writing clarity
- Also affects many plot labels

**Comment by robynforrest** [comment]
Suggest we use S for this and reserve B for total biomass which is used for the index. Currently the OM documentation uses S (although this could be changed).

**Comment by seananderson** [comment]
Although the index won’t be total biomass once we switch to the `AddInd` slot.

**Comment by robynforrest** [comment]
I will change the model documentation to B throughout to make it consistent with performance metrics
