### ISSUE TITLE
Add discussion of MP application interval

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfmp#82]
- note that recommendation remains fixed between MP application

**Comment by seananderson** [comment]
I’m assuming it will be every 2 years for a biennial survey and every year for an annual one.

**Comment by robynforrest** [comment]
Add to methods. More frequent = possibly more variable catches but otherwise should not perform too badly as long as it is a satisficed MP ...

**Comment by robynforrest** [comment]
No more frequent than survey
