### ISSUE TITLE
Decide how to add slot names to 07-dlmtool-om.Rmd

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfmp#86]
07-dlmtool-om.Rmd

L9: *TODO: Add references to slot names for user-defined parameters. Need to decide on a consistent method. E.g., do we just put the slot name in parentheses after the parameter or say something specific like "This parameter is  defined under stock@M etc. This is potentially problematic as we are giving the stock and other objects species-specific names (e.g., stock_rex@M). We could just use rex as an example. Or we could go with something generic like stock_speciesname@M*

**Comment by robynforrest** [comment]
Could also add a small table of user-defined parameters and their slot names at the end of this appendix

**Comment by seananderson** [comment]
I like the table idea.

**Comment by seananderson** [comment]
Appendix C from the MEE paper has similar tables that can serve as a reference.
