### ISSUE TITLE
Satisficing should be evaluated with # of simulations

### ISSUE THREAD

**Issue by quang-huynh** [pbs-assess/gfmp#87]
When checking convergence (whether enough simulations have been run), we should check whether the performance metric is stable with respect to the satisficing threshold, i.e., the PM should be consistently above/below the threshold with increasing simulations.

**Comment by seananderson** [comment]
I could add horizontal lines to the convergence plot and include MPs just below the threshold too.

**Comment by seananderson** [comment]
I did add those horizontal lines. It’s just then important that we use a slightly lower threshold when determining which MPs to show in the plot.
