### ISSUE TITLE
Underfishing the TAC

### ISSUE THREAD

**Issue by quang-huynh** [pbs-assess/gfmp#88]
Since industry desires high TACs, we can model this in the OM:

```
OM@TACFrac <- c(0.8, 0.8) # among sims, catch is on average 80% of the TAC
OM@TACSD <- c(0.1, 0.1) # annual CV of TACFrac is 0.1
```

These could be suitable values for the rex/shortraker examples, and would be used for all reference/robustness scenarios. For yelloweye, we would want more precise values. There didn't seem to be an answer from Tuesday's meeting, but could use recent catch relative to TAC.

Something we want to pursue?

**Comment by seananderson** [comment]
I think this is something to have in our back pocket, but I'm not sure we want to depend on industry always (or even usually) choosing not to take the TAC. For now I think we'll just assume that the TAC is taken, and if industry chooses not to do so then the MPs end of being more biologically precautionary.

**Comment by robynforrest** [comment]
Agree.
