### ISSUE TITLE
Briefly document and discuss time-varying parameters in the OM documentation

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/gfmp#93]
So far the OM documentation does not consider time-varying growth or mortality although these are options (and we may explore a time-varying M scenario for Rex).

We should probably include a note about time-varying scenarios in the om, reference point and sra documentation

**Comment by seananderson** [comment]
Yes, I think we should document the general approach, which is common for nearly all possible time-varying OM parameters.

And yes, SRA and reference point parts need their own short explanation.
